/* GRE new-standard release. Shell installation is atomic; lesson downloads are separate. */
const BUILD='117';
// BEGIN GENERATED RELEASE POLICY
// Stable IDs identify progress/history; their order here defines the learning sequence.
const STANDARD_VERSION = 'gre-deep-20261010-v1';
const APPROVED_SEQUENCE = Object.freeze([175,176,177,178,179,180,181,182,183,184]);
function gateCatalog(raw) {
 if(raw.schema!==1||!Array.isArray(raw.units)||!Array.isArray(raw.entries))throw new Error('Unsupported catalog');
 const policy=raw.learningRelease;
 if(!policy||policy.standardVersion!==STANDARD_VERSION||policy.batchSize!==10||!Array.isArray(policy.approvedIds))throw new Error('New-standard release approval missing');
 if(policy.approvedIds.length && policy.status!=='approved')throw new Error('Batch review not approved');
 if(policy.approvedIds.length%10!==0||policy.approvedIds.some((id,i)=>id!==APPROVED_SEQUENCE[i]))throw new Error('Only complete approved batches may be released');
 const seen=new Set();
 for(const entry of raw.entries){if(seen.has(entry.number))throw new Error('Duplicate canonical ID');seen.add(entry.number);}
 const entries=policy.approvedIds.map((id,i)=>{
  const entry=raw.entries.find(item=>item.number===id);
  if(!entry||entry.standardVersion!==STANDARD_VERSION||entry.reviewStatus!=='approved'||entry.textApproved!==true||entry.artApproved!==true||entry.displayOrdinal!==i+1)throw new Error('Lesson is not new-standard approved');
  if(!raw.units[entry.unit]||!entry.art?.sha256)throw new Error('Approved lesson assets missing');
  return entry;
 });
 if(raw.publishedCount!==entries.length||raw.authoredCount!==entries.length||raw.libraryTarget!==4679)throw new Error('Incorrect published lesson count');
 return {...raw,entries};
}
// END GENERATED RELEASE POLICY
// Generated by build-shell.mjs; SW is intentionally outside this non-cyclic hash list.
const SHELL_ASSETS = [{"url":"index.html","bytes":2661,"sha256":"74986dd2ef1dc279a0ff199f5df917d8fce545d4cb43c35dccf4a19de5c94807"},{"url":"manifest.webmanifest","bytes":642,"sha256":"4fb0713fe2794b661f741c27deb8b1babd2a2844e582e09fe293090d437af47a"},{"url":"icon-192-v2.png","bytes":47430,"sha256":"6e52c5115cb2e79148cf5e9df857568936987d1a9211907b9ccb10267970575b"},{"url":"gre-learning/learning.css","bytes":17612,"sha256":"9f556eea850b3ea0114a724b0354e2b48514927bb19a160b4c82423673e2b4dc"},{"url":"gre-learning/motion.css","bytes":1196,"sha256":"0181252a386847b5fca369573b38b132c1b6309662078709806e70e990dc19b5"},{"url":"gre-learning/update.js","bytes":2647,"sha256":"6610f73a7b94e135ca0709aa57c6a9684c16ccdb5cfad7ca9ed5e3da10f1f531"},{"url":"gre-learning/app.js","bytes":8845,"sha256":"c43285e435050fac429a54f5d2ba3705f84fd5d475437b0cb5b0aedf266c1a6d"},{"url":"gre-learning/catalog.json","bytes":3695,"sha256":"e830f23ab762afc25a73856a30779c642a24a59f45c9b16727909fbb7815c657"},{"url":"gre-learning/lesson-loader.js","bytes":5486,"sha256":"4db7a98fcce8658c908c229f37c23f09087527ff5f76f949a43a0157691b53ce"},{"url":"gre-learning/schema.js","bytes":4377,"sha256":"d0ba9acfa22802557f35b3e27aaba00be662bd29eec0fe737e823794027e0c37"},{"url":"gre-learning/render.js","bytes":2765,"sha256":"0390b4c083ab07106178d56c0986a47ba973d837e1480c1be9b46e6fa6ebeeeb"},{"url":"gre-learning/model.js","bytes":691,"sha256":"62a63f1c81135c717aa1f0b7c4b75a5b0dbf9d12efdfd16db28c35bf85ee900e"},{"url":"gre-learning/swipe.js","bytes":13549,"sha256":"fda18727d81bd0c90a5b07eddaec037130088d36347bdffa895b080873f9a903"},{"url":"gre-learning/motion.js","bytes":9296,"sha256":"11658380458992bc1754740baeb511b78eb897c4c09e392fdf86360e1c7e97b7"},{"url":"gre-learning/view.js","bytes":1284,"sha256":"9d747849b835007941f10dc4e30f5743bc198bf3b38a51b282a611a08e1fcc2c"},{"url":"gre-learning/motion-tracks.js","bytes":12138,"sha256":"c4fa72ae0cc4d0e91c458cd7174ba4a1ba23a7d935f352fc8cbeb583391b10fd"},{"url":"gre-learning/release-policy.js","bytes":1643,"sha256":"e007be924e2b3a1f78469ef0203bbe7609766a5194f204f84a533f0c413ee731"}];
const scope=new URL('./',self.location.href);
const SHELL_PREFIX='gre-scalable-shell-'+encodeURIComponent(scope.pathname)+'-';
const SHELL=SHELL_PREFIX+BUILD;
const UNITS='gre-scalable-verified-units-v1';
const resolve=path=>new URL(path,scope).href;
const excluded=url=>{const path=url.pathname.slice(scope.pathname.length);return /^(skyhouse|skyhouse-source)(\/|$)/.test(path);};
let catalogPromise;
async function verify(response,ref){if(!response?.ok)throw new Error('Resource unavailable');const bytes=await response.clone().arrayBuffer();if(bytes.byteLength!==ref.bytes)throw new Error('Resource size mismatch');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');if(hash!==ref.sha256)throw new Error('Resource hash mismatch');return response;}
const shellRef=url=>SHELL_ASSETS.find(ref=>resolve(ref.url)===url);
async function shellReady(){
 try{const cache=await caches.open(SHELL);for(const ref of SHELL_ASSETS)await verify(await cache.match(resolve(ref.url)),ref);return SHELL_ASSETS.length>0;}catch{return false;}
}
async function shellResponse(ref,{repair=true,requirePersistence=false}={}){
 const url=resolve(ref.url);let cache,cached;
 try{cache=await caches.open(SHELL);cached=await cache.match(url);}catch{}
 if(cached){try{return await verify(cached,ref);}catch{}}
 if(!repair)throw new Error('Shell asset is missing or corrupt');
 // Do not overwrite anything until the exact build bytes pass verification.
 const response=await fetch(url,{cache:'reload'});await verify(response,ref);
 try{if(!cache)throw new Error('Shell storage unavailable');await cache.put(url,response.clone());}
 catch(error){if(requirePersistence)throw error;}
 return response;
}
async function catalog({repair=true}={}){
 if(!catalogPromise){catalogPromise=(async()=>{const response=await shellResponse(shellRef(resolve('gre-learning/catalog.json')),{repair});return gateCatalog(await response.json());})();catalogPromise.catch(()=>{catalogPromise=null;});}
 return catalogPromise;
}
const pairRefs=(entry,data)=>[data.units[entry.unit],{...entry.art,url:`art-units/${entry.number}-${entry.art.sha256}.json`}];
async function refs(){const data=await catalog();const map=new Map();for(const entry of data.entries)for(const ref of pairRefs(entry,data))map.set(resolve('gre-learning/'+ref.url),ref);return map;}
async function broadcast(data){for(const client of await self.clients.matchAll({type:'window',includeUncontrolled:true})){const url=new URL(client.url);if(url.origin===scope.origin&&url.pathname.startsWith(scope.pathname)&&!excluded(url))client.postMessage(data);}}
self.addEventListener('install',event=>event.waitUntil((async()=>{
 const response=await fetch(resolve('gre-learning/shell-manifest.json'),{cache:'no-store'});
 if(!response.ok)throw new Error('Shell manifest unavailable');
 const manifest=await response.json();
 if(manifest.build!==BUILD)throw new Error('Shell build mismatch');
 if(JSON.stringify(manifest.assets)!==JSON.stringify(SHELL_ASSETS))throw new Error('Untrusted shell manifest');
 // New builds and same-build repairs share this verified path. Failed repairs keep every
 // still-valid asset and the preceding complete generation. Partial caches never mean ready.
 for(const ref of SHELL_ASSETS)await shellResponse(ref,{requirePersistence:true});
 if(!await shellReady())throw new Error('Incomplete shell');
 await(await caches.open(SHELL)).put(resolve('__shell_ready__'),new Response(BUILD));
})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 if(!await shellReady())throw new Error('Incomplete shell');
 const names=(await caches.keys()).filter(name=>name.startsWith(SHELL_PREFIX)&&name!==SHELL);
 const complete=[];for(const name of names){if(await(await caches.open(name)).match(resolve('__shell_ready__')))complete.push(name);}
 const previous=complete.at(-1);for(const name of names)if(name!==previous)await caches.delete(name);
 await self.clients.claim();await broadcast({type:'SHELL_READY',build:BUILD});
})()));
async function unitResponse(request,ref){let cache,cached;try{cache=await caches.open(UNITS);cached=await cache.match(request.url);}catch{}if(cached){try{return await verify(cached,ref);}catch{try{await cache.delete(request.url);}catch{}}}
 // No stale-version substitution: the old paired lesson remains intact for its old shell.
 const response=await fetch(request);await verify(response,ref);
 // Storage quota/private-mode failure must not block a valid live lesson. Readiness remains false.
 if(cache){try{await cache.put(request.url,response.clone());}catch{}}return response;
}
self.addEventListener('fetch',event=>{
 const request=event.request,url=new URL(request.url);if(request.method!=='GET'||url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname)||excluded(url))return;
 if(/\/gre-learning\/(units|art-units)\//.test(url.pathname)){
  event.respondWith((async()=>{const ref=(await refs()).get(url.href);if(!ref)return new Response('Unknown lesson unit',{status:404});try{return await unitResponse(request,ref);}catch{return new Response('Lesson unavailable offline or failed integrity validation',{status:503});}})());return;
 }
 event.respondWith((async()=>{const assetURL=new URL(request.url);assetURL.search='';const key=request.mode==='navigate'?resolve('index.html'):assetURL.href;const ref=shellRef(key);if(!ref)return fetch(request);try{return await shellResponse(ref);}catch{return new Response('Verified application shell unavailable; reconnect and retry',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});}})());
});
async function lessonStatus(){let cache;try{cache=await caches.open(UNITS);}catch{}const shellIsReady=await shellReady();let data;try{data=await catalog({repair:false});}catch{return {type:'LESSON_STATUS',build:BUILD,shellReady:false,readyIds:[],readyCount:0,availableCount:null,libraryTarget:4679,wholeTargetReady:false,error:'Verified lesson index unavailable'};}const ready=[],checked=new Map();const check=ref=>{const url=resolve('gre-learning/'+ref.url);if(!checked.has(url))checked.set(url,(async()=>{try{await verify(await cache?.match(url),ref);return true;}catch{return false;}})());return checked.get(url);};for(const entry of data.entries){let complete=true;for(const ref of pairRefs(entry,data)){if(!await check(ref)){complete=false;break;}}if(complete)ready.push(entry.number);}return {type:'LESSON_STATUS',build:BUILD,shellReady:shellIsReady,readyIds:ready,readyCount:ready.length,availableCount:data.entries.length,libraryTarget:data.libraryTarget,wholeTargetReady:shellIsReady&&ready.length===data.libraryTarget};}
self.addEventListener('message',event=>{
 const type=event.data?.type;
 if(type==='GET_BUILD'){event.ports[0]?.postMessage({type:'APP_BUILD',build:BUILD});return;}
 if(type==='SKIP_WAITING'){self.skipWaiting();return;}
 if(type==='GET_LESSON_STATUS')event.waitUntil(lessonStatus().then(value=>event.ports[0]?.postMessage(value)));
 // Explicit request only, with progress on fully verified text+art pairs. A partial download is never ready.
 if(type==='DOWNLOAD_LESSONS')event.waitUntil((async()=>{const data=await catalog();const requested=[...new Set(event.data.ids||[])].slice(0,data.entries.length);let completed=0;for(const id of requested){const entry=data.entries.find(item=>item.number===id);if(!entry)continue;try{for(const ref of pairRefs(entry,data)){const url=resolve('gre-learning/'+ref.url);await unitResponse(new Request(url),ref);await verify(await(await caches.open(UNITS)).match(url),ref);}completed++;event.ports[0]?.postMessage({type:'LESSON_DOWNLOAD_PROGRESS',completed,requested:requested.length});}catch{event.ports[0]?.postMessage({type:'LESSON_DOWNLOAD_ERROR',number:id,completed});}}event.ports[0]?.postMessage(await lessonStatus());})());
});
