/* GRE preview release. Shell installation is atomic; lesson downloads are separate. */
const BUILD='115';
// Generated by build-shell.mjs; SW is intentionally outside this non-cyclic hash list.
const SHELL_ASSETS = [{"url":"index.html","bytes":2667,"sha256":"71c26d2e8431fc66ce5fe3b0958a1a8b6a4d2590b1b35d755dac1865a0998a8f"},{"url":"manifest.webmanifest","bytes":642,"sha256":"4fb0713fe2794b661f741c27deb8b1babd2a2844e582e09fe293090d437af47a"},{"url":"icon-192-v2.png","bytes":47430,"sha256":"6e52c5115cb2e79148cf5e9df857568936987d1a9211907b9ccb10267970575b"},{"url":"gre-learning/learning.css","bytes":17612,"sha256":"9f556eea850b3ea0114a724b0354e2b48514927bb19a160b4c82423673e2b4dc"},{"url":"gre-learning/motion.css","bytes":1196,"sha256":"0181252a386847b5fca369573b38b132c1b6309662078709806e70e990dc19b5"},{"url":"gre-learning/update.js","bytes":2647,"sha256":"469f891ee2d74bd13757034c01733508e2be17a840c7a5f3f25c02ac3486787a"},{"url":"gre-learning/app.js","bytes":8484,"sha256":"bd02a8edf682be5ff768bfece9d6e1c10b059bc018fa22bc404ac467b049d122"},{"url":"gre-learning/catalog.json","bytes":40202,"sha256":"ec9cfd685c2627390a716b72492ac0f8ea2d900f587d29f3f24dd0e553a43f94"},{"url":"gre-learning/lesson-loader.js","bytes":5320,"sha256":"5f15498b465c46619132a3a261ca495b4df5087b6c4f88a82c3f6dd042b3ef99"},{"url":"gre-learning/schema.js","bytes":3257,"sha256":"e6109c3b57850aee38479f28dc70e9fc1f7ad67bcd2352354569ece949e248b1"},{"url":"gre-learning/render.js","bytes":2815,"sha256":"b1c62209e6058fc0dbdb885e5e72feefa5fba3cf2f1c095006f69298190b3b6a"},{"url":"gre-learning/model.js","bytes":691,"sha256":"62a63f1c81135c717aa1f0b7c4b75a5b0dbf9d12efdfd16db28c35bf85ee900e"},{"url":"gre-learning/swipe.js","bytes":13549,"sha256":"fda18727d81bd0c90a5b07eddaec037130088d36347bdffa895b080873f9a903"},{"url":"gre-learning/motion.js","bytes":7926,"sha256":"e304631c18371d38b56e902b07ec6d8d3fbe8ac5b6308442e8b11fd0c834a307"},{"url":"gre-learning/view.js","bytes":1284,"sha256":"9d747849b835007941f10dc4e30f5743bc198bf3b38a51b282a611a08e1fcc2c"}];
const scope=new URL('./',self.location.href);
const SHELL_PREFIX='gre-scalable-shell-'+encodeURIComponent(scope.pathname)+'-';
const SHELL=SHELL_PREFIX+BUILD;
const UNITS='gre-scalable-verified-units-v1';
const resolve=path=>new URL(path,scope).href;
const excluded=url=>{const path=url.pathname.slice(scope.pathname.length);return /^(skyhouse|skyhouse-source)(\/|$)/.test(path);};
let catalogPromise;
async function verify(response,ref){if(!response?.ok)throw new Error('Resource unavailable');const bytes=await response.clone().arrayBuffer();if(bytes.byteLength!==ref.bytes)throw new Error('Resource size mismatch');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');if(hash!==ref.sha256)throw new Error('Resource hash mismatch');return response;}
const shellRef=url=>SHELL_ASSETS.find(ref=>resolve(ref.url)===url);
async function shellReady(){
 try{const cache=await caches.open(SHELL);for(const ref of SHELL_ASSETS)await verify(await cache.match(resolve(ref.url)),ref);return SHELL_ASSETS.length>0;}catch{return false;}
}
async function shellResponse(ref,{repair=true,requirePersistence=false}={}){
 const url=resolve(ref.url);let cache,cached;
 try{cache=await caches.open(SHELL);cached=await cache.match(url);}catch{}
 if(cached){try{return await verify(cached,ref);}catch{}}
 if(!repair)throw new Error('Shell asset is missing or corrupt');
 // Do not overwrite anything until the exact build bytes pass verification.
 const response=await fetch(url,{cache:'reload'});await verify(response,ref);
 try{if(!cache)throw new Error('Shell storage unavailable');await cache.put(url,response.clone());}
 catch(error){if(requirePersistence)throw error;}
 return response;
}
async function catalog({repair=true}={}){
 if(!catalogPromise){catalogPromise=(async()=>{const response=await shellResponse(shellRef(resolve('gre-learning/catalog.json')),{repair});return response.json();})();catalogPromise.catch(()=>{catalogPromise=null;});}
 return catalogPromise;
}
const pairRefs=(entry,data)=>[data.units[entry.unit],{...entry.art,url:`art-units/${entry.number}-${entry.art.sha256}.json`}];
async function refs(){const data=await catalog();const map=new Map();for(const entry of data.entries)for(const ref of pairRefs(entry,data))map.set(resolve('gre-learning/'+ref.url),ref);return map;}
async function broadcast(data){for(const client of await self.clients.matchAll({type:'window',includeUncontrolled:true})){const url=new URL(client.url);if(url.origin===scope.origin&&url.pathname.startsWith(scope.pathname)&&!excluded(url))client.postMessage(data);}}
self.addEventListener('install',event=>event.waitUntil((async()=>{
 const response=await fetch(resolve('gre-learning/shell-manifest.json'),{cache:'no-store'});
 if(!response.ok)throw new Error('Shell manifest unavailable');
 const manifest=await response.json();
 if(manifest.build!==BUILD)throw new Error('Shell build mismatch');
 if(JSON.stringify(manifest.assets)!==JSON.stringify(SHELL_ASSETS))throw new Error('Untrusted shell manifest');
 // New builds and same-build repairs share this verified path. Failed repairs keep every
 // still-valid asset and the preceding complete generation. Partial caches never mean ready.
 for(const ref of SHELL_ASSETS)await shellResponse(ref,{requirePersistence:true});
 if(!await shellReady())throw new Error('Incomplete shell');
 await(await caches.open(SHELL)).put(resolve('__shell_ready__'),new Response(BUILD));
})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{
 if(!await shellReady())throw new Error('Incomplete shell');
 const names=(await caches.keys()).filter(name=>name.startsWith(SHELL_PREFIX)&&name!==SHELL);
 const complete=[];for(const name of names){if(await(await caches.open(name)).match(resolve('__shell_ready__')))complete.push(name);}
 const previous=complete.at(-1);for(const name of names)if(name!==previous)await caches.delete(name);
 await self.clients.claim();await broadcast({type:'SHELL_READY',build:BUILD});
})()));
async function unitResponse(request,ref){let cache,cached;try{cache=await caches.open(UNITS);cached=await cache.match(request.url);}catch{}if(cached){try{return await verify(cached,ref);}catch{try{await cache.delete(request.url);}catch{}}}
 // No stale-version substitution: the old paired lesson remains intact for its old shell.
 const response=await fetch(request);await verify(response,ref);
 // Storage quota/private-mode failure must not block a valid live lesson. Readiness remains false.
 if(cache){try{await cache.put(request.url,response.clone());}catch{}}return response;
}
self.addEventListener('fetch',event=>{
 const request=event.request,url=new URL(request.url);if(request.method!=='GET'||url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname)||excluded(url))return;
 if(/\/gre-learning\/(units|art-units)\//.test(url.pathname)){
  event.respondWith((async()=>{const ref=(await refs()).get(url.href);if(!ref)return new Response('Unknown lesson unit',{status:404});try{return await unitResponse(request,ref);}catch{return new Response('Lesson unavailable offline or failed integrity validation',{status:503});}})());return;
 }
 event.respondWith((async()=>{const assetURL=new URL(request.url);assetURL.search='';const key=request.mode==='navigate'?resolve('index.html'):assetURL.href;const ref=shellRef(key);if(!ref)return fetch(request);try{return await shellResponse(ref);}catch{return new Response('Verified application shell unavailable; reconnect and retry',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});}})());
});
async function lessonStatus(){let cache;try{cache=await caches.open(UNITS);}catch{}const shellIsReady=await shellReady();let data;try{data=await catalog({repair:false});}catch{return {type:'LESSON_STATUS',build:BUILD,shellReady:false,readyIds:[],readyCount:0,availableCount:null,libraryTarget:4679,wholeTargetReady:false,error:'Verified lesson index unavailable'};}const ready=[],checked=new Map();const check=ref=>{const url=resolve('gre-learning/'+ref.url);if(!checked.has(url))checked.set(url,(async()=>{try{await verify(await cache?.match(url),ref);return true;}catch{return false;}})());return checked.get(url);};for(const entry of data.entries){let complete=true;for(const ref of pairRefs(entry,data)){if(!await check(ref)){complete=false;break;}}if(complete)ready.push(entry.number);}return {type:'LESSON_STATUS',build:BUILD,shellReady:shellIsReady,readyIds:ready,readyCount:ready.length,availableCount:data.entries.length,libraryTarget:data.libraryTarget,wholeTargetReady:shellIsReady&&ready.length===data.libraryTarget};}
self.addEventListener('message',event=>{
 const type=event.data?.type;
 if(type==='GET_BUILD'){event.ports[0]?.postMessage({type:'APP_BUILD',build:BUILD});return;}
 if(type==='SKIP_WAITING'){self.skipWaiting();return;}
 if(type==='GET_LESSON_STATUS')event.waitUntil(lessonStatus().then(value=>event.ports[0]?.postMessage(value)));
 // Explicit request only, with progress on fully verified text+art pairs. A partial download is never ready.
 if(type==='DOWNLOAD_LESSONS')event.waitUntil((async()=>{const data=await catalog();const requested=[...new Set(event.data.ids||[])].slice(0,data.entries.length);let completed=0;for(const id of requested){const entry=data.entries.find(item=>item.number===id);if(!entry)continue;try{for(const ref of pairRefs(entry,data)){const url=resolve('gre-learning/'+ref.url);await unitResponse(new Request(url),ref);await verify(await(await caches.open(UNITS)).match(url),ref);}completed++;event.ports[0]?.postMessage({type:'LESSON_DOWNLOAD_PROGRESS',completed,requested:requested.length});}catch{event.ports[0]?.postMessage({type:'LESSON_DOWNLOAD_ERROR',number:id,completed});}}event.ports[0]?.postMessage(await lessonStatus());})());
});
