// Bounded inert retained SVG tracks for the six acceptance scenes only.
const allowedWords={175:'avarice',176:'aver',177:'aversion',178:'avid',179:'awash',180:'awe'};
const tags=new Set('g path rect circle ellipse line polyline polygon text defs clipPath linearGradient radialGradient stop'.split(' '));
const dynamic=new Set('d transform opacity x y cx cy r rx ry width height'.split(' '));
const attributes=new Set('d points transform opacity x y cx cy r rx ry x1 y1 x2 y2 width height fill stroke stroke-width stroke-linecap stroke-linejoin fill-rule clip-rule clip-path clipPathUnits gradientUnits gradientTransform offset stop-color stop-opacity font-family font-size font-weight text-anchor dominant-baseline'.split(' '));
const arities={M:2,L:2,H:1,V:1,Q:4,C:6,S:4,T:2,Z:0};
const numberRE=/[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?/g;
const idRE=/^[A-Za-z][A-Za-z0-9_-]{0,63}$/;
const rootKeys=new Set('schema number word example visual viewBox durationMs beforeTimeMs reducedTimeMs nodes tracks'.split(' '));
const fail=message=>{throw new TypeError('Invalid tracked art: '+message)};
const shape=(value,keys,label)=>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>!keys.has(k)))fail(label)};
const finite=(value,min,max,label)=>{if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)fail(label);return value};
const text=(value,max,label)=>{if(typeof value!=='string'||!value.trim()||value.length>max)fail(label);return value};
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function numbers(value){const s=String(value),tokens=s.match(numberRE)||[];if(s.replace(numberRE,'').replace(/[\s,]/g,''))fail('numeric syntax');return tokens.map(Number)}
function pathSpec(value){const s=String(value);if(s.length>16384)fail('path length');const tokens=s.match(/[MLHVQCSTZ]|[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?/g)||[];if(tokens.join('')!==s.replace(/[\s,]/g,'')||tokens[0]!=='M')fail('path syntax');let i=0,values=[],signature=[];while(i<tokens.length){const cmd=tokens[i++];if(!(cmd in arities))fail('path command');signature.push(cmd);for(let n=0;n<arities[cmd];n++){if(i>=tokens.length||tokens[i]in arities)fail('path arity');const v=Number(tokens[i++]);finite(v,-1440,1440,'path coordinate');values.push(v)}}return{values,signature:signature.join(''),bounds:values.map(()=>[-1440,1440])}}
function transformSpec(value){const s=String(value);if(s.length>4096)fail('transform length');if(!s.trim())return{values:[],signature:'',bounds:[]};let pos=0,values=[],bounds=[],signature=[];const re=/(translate|rotate|scale|matrix)\(([^()]*)\)/g;let m;while((m=re.exec(s))){if(s.slice(pos,m.index).trim())fail('transform syntax');pos=re.lastIndex;const a=numbers(m[2]),op=m[1];if(!({translate:[2],rotate:[1,3],scale:[1,2],matrix:[6]}[op]).includes(a.length))fail('transform arity');signature.push(op+a.length);a.forEach((v,i)=>{const bound=op==='rotate'&&i===0?720:op==='scale'||op==='matrix'&&i<4?8:1440;finite(v,-bound,bound,'transform value');values.push(v);bounds.push([-bound,bound])});if(signature.length>32)fail('transform operations')}if(s.slice(pos).trim()||!signature.length)fail('transform syntax');return{values,bounds,signature:signature.join(' ')}}
function scalarBounds(attribute){return attribute==='opacity'||attribute==='stop-opacity'||attribute==='offset'?[0,1]:['r','rx','ry','width','height'].includes(attribute)?[0,1440]:attribute==='stroke-width'?[0,32]:attribute==='font-size'?[16,48]:[-1440,1440]}
function spec(attribute,value){if(attribute==='d')return pathSpec(value);if(attribute==='transform'||attribute==='gradientTransform')return transformSpec(value);if(attribute==='points'){const a=numbers(value);if(a.length<4||a.length%2||a.length>512)fail('points');a.forEach(v=>finite(v,-1440,1440,'point'));return{values:a,signature:'points'+a.length,bounds:a.map(()=>[-1440,1440])}}const a=numbers(value),bound=scalarBounds(attribute);if(a.length!==1)fail('scalar arity');finite(a[0],...bound,attribute);return{values:a,signature:'scalar',bounds:[bound]}}
const refRE=/^url\(#([A-Za-z][A-Za-z0-9_-]{0,63})\)$/;
function validateAttribute(key,value,refs){if(typeof value!=='string'&&typeof value!=='number')fail('attribute value');if(typeof value==='number'&&!Number.isFinite(value))fail('attribute finite');const s=String(value);if(s.length>16384)fail('attribute length');if(['fill','stroke','stop-color'].includes(key)){const r=s.match(refRE);if(r){refs.push({id:r[1],kind:'gradient'});return}if(!/^(?:#(?:[\da-fA-F]{3}|[\da-fA-F]{6}|[\da-fA-F]{8})|none|transparent|currentColor)$/.test(s))fail('paint');return}if(key==='clip-path'){const r=s.match(refRE);if(!r)fail('clip reference');refs.push({id:r[1],kind:'clipPath'});return}const enums={'stroke-linecap':['butt','round','square'],'stroke-linejoin':['miter','round','bevel'],'fill-rule':['nonzero','evenodd'],'clip-rule':['nonzero','evenodd'],clipPathUnits:['userSpaceOnUse','objectBoundingBox'],gradientUnits:['userSpaceOnUse','objectBoundingBox'],'text-anchor':['start','middle','end'],'dominant-baseline':['auto','middle','central','hanging','text-before-edge','alphabetic'],'font-weight':['normal','bold','400','500','600','700']};if(enums[key]){if(!enums[key].includes(s))fail(key);return}if(key==='font-family'){if(!/^[A-Za-z0-9 ,"'-]{1,160}$/.test(s))fail('font family');return}spec(key,value)}
const supports=(tag,attribute)=>attribute==='transform'||attribute==='opacity'||attribute==='d'&&tag==='path'||['x','y','width','height'].includes(attribute)&&tag==='rect'||['x','y'].includes(attribute)&&tag==='text'||['cx','cy'].includes(attribute)&&['circle','ellipse'].includes(tag)||attribute==='r'&&tag==='circle'||['rx','ry'].includes(attribute)&&['ellipse','rect'].includes(tag);
export function trackAttribute(track,values){let s=track.parts[0];for(let i=0;i<values.length;i++)s+=String(Math.round(values[i]*1e6)/1e6)+track.parts[i+1];return s}
export function sampleTrack(track,time){const samples=track.samples;if(time<=samples[0][0])return samples[0][1];if(time>=samples.at(-1)[0])return samples.at(-1)[1];let lo=0,hi=samples.length-1;while(hi-lo>1){const mid=(lo+hi)>>1;if(samples[mid][0]<=time)lo=mid;else hi=mid}const a=samples[lo],b=samples[hi],p=(time-a[0])/(b[0]-a[0]);return a[1].map((v,i)=>v+(b[1][i]-v)*p)}
export function validateTrackedArt(art){shape(art,rootKeys,'root');if(art.schema!==2||!Number.isSafeInteger(art.number)||allowedWords[art.number]!==art.word)fail('scene identity');if(!Array.isArray(art.viewBox)||art.viewBox.length!==4||art.viewBox[0]!==0||art.viewBox[1]!==0||art.viewBox[2]!==360)fail('viewBox');finite(art.viewBox[3],200,480,'height');finite(art.durationMs,2000,30000,'duration');finite(art.beforeTimeMs,0,art.durationMs,'before time');finite(art.reducedTimeMs,0,art.durationMs,'reduced time');shape(art.example,new Set(['word','before','after','summary']),'example');if(art.example.word!==art.word)fail('example identity');for(const key of ['before','after','summary'])text(art.example[key],1200,'description');shape(art.visual,new Set(['alt']),'visual');text(art.visual.alt,1200,'visual alt');const byId=new Map(),refs=[];let count=0;
 function visit(node,depth){shape(node,new Set(['id','tag','attrs','children','text']),'node');if(depth>16||++count>256||typeof node.id!=='string'||!idRE.test(node.id)||byId.has(node.id)||!tags.has(node.tag))fail('node identity/bounds');shape(node.attrs,attributes,'attributes');byId.set(node.id,node);for(const [key,value]of Object.entries(node.attrs))validateAttribute(key,value,refs);if(node.text!==undefined){if(node.tag!=='text')fail('text tag');text(node.text,160,'node text')}if(node.tag==='text'&&node.text===undefined)fail('missing static text');if(node.children!==undefined){if(!Array.isArray(node.children)||node.tag==='text'&&node.children.length)fail('children');for(const child of node.children)visit(child,depth+1)}}
 if(!Array.isArray(art.nodes)||!art.nodes.length)fail('nodes');for(const node of art.nodes)visit(node,1);for(const ref of refs){const target=byId.get(ref.id);if(!target||ref.kind==='clipPath'&&target.tag!=='clipPath'||ref.kind==='gradient'&&!['linearGradient','radialGradient'].includes(target.tag))fail('unresolved reference')}
 if(!Array.isArray(art.tracks)||art.tracks.length>128)fail('tracks');const seen=new Set();let stored=0;for(const track of art.tracks){shape(track,new Set(['target','attribute','parts','samples']),'track');if(typeof track.target!=='string')fail('track target type');const node=byId.get(track.target),key=track.target+'|'+track.attribute;if(!node||!dynamic.has(track.attribute)||!supports(node.tag,track.attribute)||seen.has(key)||node.attrs[track.attribute]===undefined)fail('track target');seen.add(key);if(!Array.isArray(track.parts)||track.parts.length<2||track.parts.length>129||track.parts.some(p=>typeof p!=='string'||p.length>1024||/[\d.+\-]/.test(p)))fail('template parts');if(!Array.isArray(track.samples)||track.samples.length<2||track.samples.length>2048)fail('samples');const slots=track.parts.length-1,initial=spec(track.attribute,node.attrs[track.attribute]),probe=spec(track.attribute,trackAttribute(track,Array(slots).fill(track.attribute==='width'||track.attribute==='height'?1:0)));if(initial.values.length!==slots||probe.values.length!==slots||initial.signature!==probe.signature)fail('fixed template');if(!['d','transform'].includes(track.attribute)&&(track.parts[0]!==''||track.parts[1]!==''||slots!==1))fail('scalar template');let prior=-1;for(const sample of track.samples){if(!Array.isArray(sample)||sample.length!==2||!Array.isArray(sample[1])||sample[1].length!==slots)fail('sample shape');finite(sample[0],0,art.durationMs,'sample time');if(sample[0]<=prior)fail('sample order');prior=sample[0];for(let i=0;i<slots;i++)finite(sample[1][i],...initial.bounds[i],'sample value');stored+=slots;if(stored>400000)fail('numeric sample budget')}if(track.samples[0][0]!==0||track.samples.at(-1)[0]!==art.durationMs)fail('sample endpoints');if(initial.values.some((v,i)=>Math.abs(v-track.samples[0][1][i])>1e-6))fail('initial sample mismatch')}
 if(new TextEncoder().encode(JSON.stringify(art)).byteLength>2*1024*1024)fail('raw JSON budget');
 return art;
}
const textStyles=['font-family','font-size','font-weight','text-anchor','fill','stroke','stroke-width'];
export function renderTrackedArtwork(art,prefix,time){const sampled=new Map();for(const track of art.tracks){if(!sampled.has(track.target))sampled.set(track.target,{});sampled.get(track.target)[track.attribute]=trackAttribute(track,sampleTrack(track,time))}const reference=value=>String(value).replace(refRE,(_,id)=>`url(#${prefix}-node-${id})`);function nodeHTML(node,inherited={}){const attrs={...node.attrs,...sampled.get(node.id)};const inheritedStyles={...inherited,...Object.fromEntries(textStyles.filter(k=>attrs[k]!==undefined).map(k=>[k,attrs[k]]))};let s=`<${node.tag} id="${prefix}-node-${node.id}" data-track-node="${node.id}"`;for(const[key,value]of Object.entries(attrs))s+=` ${key}="${esc(reference(value))}"`;if(node.tag==='text'){const defaults={'font-family':'serif','font-size':16,'font-weight':400,'text-anchor':'start',fill:'#000',stroke:'none','stroke-width':1};const styles={...defaults,...inheritedStyles};s+=' style="'+esc(textStyles.filter(k=>styles[k]!==undefined).map(k=>`${k}:${k==='font-size'?styles[k]+'px':reference(styles[k])}`).join(';'))+'"'}s+='>';if(node.text!==undefined)s+=esc(node.text);for(const child of node.children||[])s+=nodeHTML(child,inheritedStyles);return s+`</${node.tag}>`}return art.nodes.map(node=>nodeHTML(node)).join('')}
export function collectTrackedStage(stage,art){return art.tracks.map(track=>{const element=stage.querySelector(`[data-track-node="${track.target}"]`);if(!element)fail('mounted target');return{track,element,last:null}})}
export function paintTrackedStage(targets,time){for(const item of targets){const value=trackAttribute(item.track,sampleTrack(item.track,time));if(value!==item.last){item.element.setAttribute(item.track.attribute,value);item.last=value}}}
