import {sceneGlosses} from './scene-glosses.js';
const escape = value => String(value??'').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const arrow = direction => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${direction==='previous'?'m14 6-6 6 6 6':'m10 6 6 6-6 6'}"/></svg>`;
const speakIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m10 5-5 4H2v6h3l5 4V5ZM14 8c2 2 2 6 0 8M18 5c4 4 4 10 0 14"/></svg>';
function paragraphs(text){return text.split(/(?<=[。！？])(?=[^”’])/).filter(Boolean);}
function method(item,i){
 const [kind,...title]=item.method.split('｜');
 return `<article class="mnemonic"><div class="mnemonic-heading"><span class="mnemonic-marker" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div><p class="method-kind">${escape(kind)}</p><h3>${escape(title.join('｜')||kind)}</h3></div></div><p>${escape(item.textZh)}</p></article>`;
}
function artwork(entry,media){
 if(!media)return '<div class="story-illustration illustration-pending" aria-hidden="true"></div>';
 return `<figure class="story-illustration" style="--media-ratio:${media.width}/${media.height}">${media.stages?`<figcaption class="story-dialogue-band"><span class="story-dialogue speaker-left" style="--dialogue-x:${media.posterDialogue?.anchor?.x||.34}" data-story-dialogue>${escape(media.posterDialogue.text)}</span></figcaption>`:''}<div class="illustration-art"><img class="story-poster" src="${escape(media.posterURL)}" width="${media.width}" height="${media.height}" alt="${escape(media.alt||entry.coreImageZh)}" decoding="async">${media.videoURL?`<video class="story-video" data-story-video src="${escape(media.videoURL)}" poster="${escape(media.posterURL)}" width="${media.width}" height="${media.height}" autoplay muted loop playsinline preload="auto" aria-hidden="true"></video><button type="button" class="motion-toggle" data-motion-toggle aria-label="暂停插画动画" aria-pressed="false"><svg class="pause-symbol" viewBox="0 0 20 20" aria-hidden="true"><path d="M7 5v10M13 5v10"/></svg><svg class="play-symbol" viewBox="0 0 20 20" aria-hidden="true"><path d="m7 4 9 6-9 6Z"/></svg></button>`:''}</div></figure>`;
}
function chapter(id,number,title,body){return `<section class="book-chapter" id="${id}" aria-labelledby="${id}-title"><header class="chapter-heading"><span class="chapter-index" aria-hidden="true">${number}</span><h2 id="${id}-title">${title}</h2></header>${body}</section>`;}
export function renderWordPage(entry,media,position){
 const story=paragraphs(entry.coreImageZh),lead=story.shift()||entry.coreImageZh;
 return `<article class="reading-layout" aria-labelledby="word-title"><div class="book-spread"><section class="opening-page"><header class="word-hero"><h1 id="word-title" lang="en">${escape(entry.word)}</h1><div class="word-meta"><span class="pronunciation">${escape(entry.ipa)}</span><button type="button" class="pronounce-button" data-speak aria-label="朗读 ${escape(entry.word)}">${speakIcon}</button></div><p class="part-of-speech">${escape(entry.pos)}</p></header>${artwork(entry,media)}<div class="scene-opening"><h2 class="word-meaning">${escape(sceneGlosses[entry.number]||entry.coreMeaningZh)}</h2><p class="english-meaning" lang="en">${escape(entry.coreEn)}</p><p class="scene-lead">${escape(entry.coreImageZh)}</p></div></section><section class="memory-page" id="memory" aria-label="词汇助记与图景解读"><div class="mnemonics">${entry.mnemonics.map(method).join('')}</div></section><div class="spread-pagination" aria-label="单词翻页"><button class="page-turn" type="button" data-page="previous" ${!position.previous?'disabled':''} aria-label="上一个单词">${arrow('previous')}<span>上一页</span></button><span class="folio">${String(position.index+1).padStart(2,'0')}<i aria-hidden="true">/</i>${String(position.total).padStart(2,'0')}</span><button class="page-turn" type="button" data-page="next" ${!position.next?'disabled':''} aria-label="下一个单词"><span>下一页</span>${arrow('next')}</button></div></div><div class="book-continuation">${chapter('usage','01','核心用法与词组',`<div class="complete-meaning"><p>${escape(entry.coreMeaningZh)}</p></div>`+entry.usage.map(item=>`<article class="sense"><h3>${escape(item.senseZh)}</h3><p>${escape(item.explanationZh)}</p>${item.collocations.length?`<dl class="collocations">${item.collocations.map(c=>`<div><dt lang="en">${escape(c.phrase)}</dt><dd>${escape(c.meaningZh)}${c.usageZh?`<small>${escape(c.usageZh)}</small>`:''}</dd></div>`).join('')}</dl>`:''}</article>`).join(''))}${chapter('context-examples','02','语境例句',entry.examples.map((item,i)=>`<figure class="example"><span class="example-number" aria-hidden="true">${i+1}</span><blockquote lang="en">${escape(item.textEn)}</blockquote><figcaption>${escape(item.translationZh)}</figcaption><p class="example-note">${escape(item.explanationZh)}</p></figure>`).join(''))}${chapter('comparison','03','GRE 等价词',`<div class="equivalents">${entry.equivalents.map(item=>`<article class="equivalent"><h3 lang="en">${escape(item.word)}</h3><p>${escape(item.comparisonZh)}</p></article>`).join('')}</div>`)}<footer class="reading-end"><span aria-hidden="true">✦</span><button type="button" data-section="word-title">回到这一页的开头 ↑</button></footer></div></article>`;
}
