import {sceneGlosses} from './scene-glosses.js';
const escape = value => String(value??'').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const speakIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m10 5-5 4H2v6h3l5 4V5ZM14 8c2 2 2 6 0 8M18 5c4 4 4 10 0 14"/></svg>';
function paragraphs(text){return text.split(/(?<=[。！？])(?=[^”’])/).filter(Boolean);}
function method(item){
 const [kind,...title]=item.method.split('｜');
 return `<article class="mnemonic"><div class="mnemonic-heading"><div><p class="method-kind">${escape(kind)}</p><h3>${escape(title.join('｜')||kind)}</h3></div></div><p>${escape(item.textZh)}</p></article>`;
}
function artwork(entry,media){
 if(!media)return '<div class="story-illustration illustration-pending" aria-hidden="true"></div>';
 return `<figure class="story-illustration" style="--media-ratio:${media.width}/${media.height}"><figcaption class="story-dialogue-band" ${!media.stages?'aria-hidden="true"':''}>${media.stages?`<span class="story-dialogue speaker-left" style="--dialogue-x:${media.posterDialogue?.anchor?.x||.34}" data-story-dialogue>${escape(media.posterDialogue.text)}</span>`:''}</figcaption><div class="illustration-art"><img class="story-poster" src="${escape(media.posterURL)}" width="${media.width}" height="${media.height}" alt="${escape(media.alt||entry.coreImageZh)}" decoding="async">${media.videoURL?`<video class="story-video" data-story-video src="${escape(media.videoURL)}" poster="${escape(media.posterURL)}" width="${media.width}" height="${media.height}" muted loop playsinline preload="auto" aria-hidden="true"></video>`:''}</div></figure>`;
}
function chapter(id,title,body){return `<section class="book-chapter" id="${id}" aria-labelledby="${id}-title"><header class="chapter-heading"><h2 id="${id}-title">${title}</h2></header>${body}</section>`;}
export function renderWordPage(entry,media,position){
 const story=paragraphs(entry.coreImageZh),lead=story.shift()||entry.coreImageZh;
 return `<article class="reading-layout" aria-labelledby="word-title"><div class="book-spread"><section class="opening-page"><header class="word-hero${entry.word.length>=10?' has-long-headword':''}"><h1 id="word-title" lang="en"${entry.word.length>=10?` class="long-headword" style="--headword-fit:${(entry.word.length*.55).toFixed(2)}"`:''}>${escape(entry.word)}</h1><div class="word-meta"><span class="pronunciation">${escape(entry.ipa)}</span><button type="button" class="pronounce-button" data-speak aria-label="朗读 ${escape(entry.word)}">${speakIcon}</button></div><p class="part-of-speech">${escape(entry.pos)}</p></header>${artwork(entry,media)}</section><section class="memory-page" id="memory" aria-label="词义与词汇助记"><div class="scene-opening"><h2 class="word-meaning">${escape(sceneGlosses[entry.number]||entry.coreMeaningZh)}</h2><p class="english-meaning" lang="en">${escape(entry.coreEn)}</p><p class="scene-lead">${escape(entry.coreImageZh)}</p></div><div class="mnemonics">${entry.mnemonics.map(method).join('')}</div></section></div><div class="book-continuation">${chapter('usage','核心用法与词组',entry.usage.map(item=>`<article class="sense"><h3>${escape(item.senseZh)}</h3><p>${escape(item.explanationZh)}</p>${item.collocations.length?`<dl class="collocations">${item.collocations.map(c=>`<div><dt lang="en">${escape(c.phrase)}</dt><dd>${escape(c.meaningZh)}${c.usageZh?`<small>${escape(c.usageZh)}</small>`:''}</dd></div>`).join('')}</dl>`:''}</article>`).join(''))}${chapter('context-examples','语境例句',entry.examples.map(item=>`<figure class="example"><blockquote lang="en">${escape(item.textEn)}</blockquote><figcaption>${escape(item.translationZh)}</figcaption><p class="example-note">${escape(item.explanationZh)}</p></figure>`).join(''))}${chapter('comparison','GRE 等价词',`<div class="equivalents">${entry.equivalents.length?entry.equivalents.map(item=>`<article class="equivalent"><h3 lang="en">${escape(item.word)}${item.source==='zhangwei_dedicated_2021'?'<span class="equivalent-source" lang="zh" role="img" aria-label="张巍资料" title="张巍资料">张</span>':''}</h3><p>${escape(item.comparisonZh)}</p></article>`).join(''):'<article class="equivalent"><p class="equivalents-empty">暂无适合本义的等价词</p></article>'}</div>`)}<footer class="reading-end"><span aria-hidden="true">✦</span><button type="button" data-section="word-title">回到这一页的开头 ↑</button></footer></div></article>`;
}
